theme: jekyll-theme-cayman
include:
  - _layouts
  - _includes
  - assets
  - docs
sass:
  sass_dir: assets/css
  style: compressed  # Optional: Compresses CSS
kramdown:
  toc_levels: 1..3  # Enables Table of Contents for H1, H2, H3
